services:
    mindy.bundle.seo.provider.seo:
        class: Mindy\Bundle\SeoBundle\Provider\SeoProvider

    seo.seo.form:
        class: Mindy\Bundle\SeoBundle\Form\SeoFormType
        arguments: [ '@request_stack' ]
        tags:
            - { name: form.type }

    seo.seo.inline_form:
        class: Mindy\Bundle\SeoBundle\Form\SeoInlineFormType
        arguments: [ '@request_stack' ]
        tags:
            - { name: form.type }

    mindy.bundle.seo.registry:
        class: Mindy\Bundle\SeoBundle\Meta\Registry

    mindy.bundle.seo.helper.seo:
        class: Mindy\Bundle\SeoBundle\Helper\SeoHelper

    mindy.bundle.seo.event_subscriber.seo:
        class: Mindy\Bundle\SeoBundle\EventListener\SeoEventSubscriber
        arguments:
            - '@mindy.bundle.seo.provider.seo'
            - '@request_stack'

    mindy.bundle.seo.template.seo.library:
        class: Mindy\Bundle\SeoBundle\Library\SeoLibrary
        arguments:
            - '@request_stack'
            - '@mindy.bundle.seo.provider.seo'
            - '@templating.engine.mindy'
        tags:
            - { name: template.library }

    mindy.bundle.seo.admin.seo:
        class: Mindy\Bundle\SeoBundle\Admin\SeoAdmin
        tags:
            - { name: admin.admin, slug: seo_seo }

    mindy.bundle.seo.admin.template:
        class: Mindy\Bundle\SeoBundle\Admin\TemplateAdmin
        tags:
            - { name: admin.admin, slug: seo_template }