services:
    meta.meta_provider:
        class: Mindy\Bundle\MetaBundle\Provider\MetaProvider

    meta.meta.form:
        class: Mindy\Bundle\MetaBundle\Form\MetaFormType
        arguments: [ '@request_stack' ]
        tags:
            - { name: form.type }

    meta.template.meta.library:
        class: Mindy\Bundle\MetaBundle\Library\MetaLibrary
        arguments: [ '@request_stack', '@meta.meta_provider', '@template' ]
        tags:
            - { name: template.library }

    meta.admin.meta:
        class: Mindy\Bundle\MetaBundle\Admin\MetaAdmin
        tags:
            - { name: admin.admin, slug: meta_meta }

    meta.admin.template:
        class: Mindy\Bundle\MetaBundle\Admin\TemplateAdmin
        tags:
            - { name: admin.admin, slug: meta_template }