services:
    admin.registry:
        class: Mindy\Bundle\MindyBundle\Admin\AdminRegistry

    admin:
        class: Mindy\Bundle\MindyBundle\Admin\AdminManager
        arguments: [ '@kernel', '@admin.template.finder' ]

    admin.menu:
        class: Mindy\Bundle\MindyBundle\Admin\AdminMenu
        arguments: [ "%admin.menu%" ]

    admin.template.finder:
        class: Mindy\Bundle\MindyBundle\Admin\AdminTemplateFinder
        arguments: [ '@template.finder.chain' ]
        public: false

    admin.user_provider:
        class: Mindy\Bundle\MindyBundle\Provider\UserProvider

    template.admin.library:
        class: Mindy\Bundle\MindyBundle\Library\AdminLibrary
        arguments:
            - '@admin.menu'
            - '@template'
        tags:
            - { name: template.library }