admin_index:
    path: /
    defaults: { _controller: AdminBundle:Admin:index }

admin_dispatch:
    path: /{bundle}/{admin}/{action}
    defaults: { _controller: AdminBundle:Admin:dispatch }
    requirements:
        bundle: \w+
        admin: \w+
        action: \w+

admin_login:
    path: /login
    defaults: { _controller: AdminBundle:Admin:login }

admin_logout:
    path: /logout
    defaults: { _controller: AdminBundle:Admin:logout }