admin_index:
    path: /
    defaults: { _controller: AdminBundle:Admin:index }

admin_login:
    path: /login
    defaults: { _controller: AdminBundle:Admin:login }

admin_logout:
    path: /logout
    defaults: { _controller: AdminBundle:Admin:logout }

admin_dispatch:
    path: /{admin}/{action}
    defaults:
        _controller: AdminBundle:Admin:dispatch
        action: 'list'
    requirements:
        admin: \w+
        action: \w+