services:
    admin.registry:
        class: Mindy\Bundle\AdminBundle\Admin\AdminRegistry

    admin.menu:
        class: Mindy\Bundle\AdminBundle\Admin\AdminMenu
        arguments: [ "%admin.menu%" ]

    admin.template.finder:
        class: Mindy\Bundle\AdminBundle\Admin\AdminTemplateFinder
        arguments: [ '@template.finder.chain' ]

    template.admin.library:
        class: Mindy\Bundle\AdminBundle\Library\AdminLibrary
        arguments: [ '@admin.menu', '@template' ]
        tags:
            - { name: template.library }

    admin.dashboard.admin_menu:
        class: Mindy\Bundle\AdminBundle\Dashboard\AdminMenuWidget
        arguments: [ '@admin.menu' ]
        tags:
            - { name: admin.dashboard.widget }